Add test and Docs for angle property on Attached Components class
CeuAzul/ADR pull request #250
Opened 2020-09-03 20:22 UTC by joaofoes

2020-09-03 20:51 UTC, joaofoes commented
Ahm, don't quite know where the test failed.

2020-09-04 21:21 UTC, rafaellehmkuhl commented
From travis:

```python
def test_angle(attached_component, freebody_component):
        attached_component.set_parent(freebody_component)
        angle = math.degrees(attached_component.angle)
        assert(angle == 14)
        attached_component.actuation_angle = math.radians(10)
        angle = math.degrees(attached_component.angle)
>       assert(angle == 24)
E       assert 24.000000000000004 == 24
```

It's just a float precision problem. Can you substitute the ```assert``` function for the ```numpy.testing.assert_almost_equal()```?

2020-09-04 21:30 UTC, rafaellehmkuhl requested changes

2020-09-04 21:30 UTC, rafaellehmkuhl commented on docs/Components/AttachedComponent.md
> +Let's say we have a component 'Wing' attached to the body of the plane, that it's set as a FreeBody Component called 'Plane'. The property angle will take in count the plane angle and the relative an
typo: [...] that is set as [...]

2020-09-04 21:30 UTC, rafaellehmkuhl commented on docs/Components/AttachedComponent.md
> +>>> 4.2
Despite being possible to set the "relative_angle" property after the component instantiation, we are setting as a convention to always set it on instantiation, together with relative_position.

In the future we are going to make this mandatory, so the user always set it and the library don't face calculation problems.

2020-09-04 21:30 UTC, rafaellehmkuhl commented on docs/Components/AttachedComponent.md
> +>>> 19.2
Nice catch!

2020-09-04 21:30 UTC, rafaellehmkuhl commented on tests/Components/test_AttachedComponent.py
> +from adr.Components import FreeBody
Import those on the same line.

2020-09-07 13:47 UTC, CassianoMontibeller approved these changes

2020-09-07 17:21 UTC, rafaellehmkuhl approved these changes

2020-09-07 17:27 UTC, merged