Add test and docs for add external force function
CeuAzul/ADR pull request #253
Opened 2020-09-08 22:19 UTC by CassianoMontibeller

2020-09-08 22:44 UTC, rafaellehmkuhl requested changes

2020-09-08 22:44 UTC, rafaellehmkuhl commented on docs/Components/BaseComponent.md
> +This function is responsible for adding an external force applied to a given point on the component
This *method is responsible for *appending an external force *function to the component. *The force function returns a force vector and an application point.

2020-09-08 22:44 UTC, rafaellehmkuhl commented on tests/Components/test_BaseComponent.py
> +
Remove this line.

2020-09-08 22:44 UTC, rafaellehmkuhl commented on tests/Components/test_BaseComponent.py
> +
Nice

2020-09-08 22:44 UTC, rafaellehmkuhl commented on tests/Components/test_BaseComponent.py
> +    assert(base_component.external_forces['force1'] == force1)
Perfect!

2020-09-08 22:44 UTC, rafaellehmkuhl commented on tests/Components/test_BaseComponent.py
> +    assert(base_component.external_forces == {'force1': force1})
This assert is not needed

2020-09-11 15:03 UTC, rafaellehmkuhl approved these changes

2020-09-11 22:34 UTC, joaofoes approved these changes

2020-09-11 23:57 UTC, merged