Add test for add_external_moment_function
CeuAzul/ADR pull request #259
Opened 2020-09-11 04:07 UTC by joaofoes

2020-09-11 04:10 UTC, joaofoes commented
the branch has given a conflict but no idea why... everything stayed the same, didn't deleted any line or changed any typing pattern. thinking here ...

2020-09-11 15:11 UTC, rafaellehmkuhl requested changes

2020-09-11 15:11 UTC, rafaellehmkuhl commented on tests/Components/test_BaseComponent.py
> +
Moments do not have a point of application, physically speaking, so you can remove *moment_point* instantiation and return.

About the moment being a vector, it is not physically wrong, but ADR currently deals with 2D physics only, so we consider the moment a scalar (just having magnitude) and always assume that it acts on the Z-axis (pitch). On future versions we will probably introduce 3D and consider moments as vectors.

2020-09-11 23:33 UTC, CassianoMontibeller approved these changes

2020-09-12 00:04 UTC, rafaellehmkuhl approved these changes

2020-09-12 00:16 UTC, merged